# Generated by Django 3.2.13 on 2024-09-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GradeThresholds',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('less_than_threshold_grade_A', models.IntegerField(default=2, help_text='Any score less than this will result in a letter grade of A', verbose_name='Letter Grade A - Less than')),
                ('greater_eq_threshold_grade_B', models.IntegerField(default=2, help_text='Any score greater than this will result in a letter grade of B', verbose_name='Letter Grade B - Greater or equal to')),
                ('less_than_threshold_grade_B', models.IntegerField(default=4, help_text='Any score less than this will result in a Letter Grade of B', verbose_name='and less than')),
                ('greater_eq_threshold_grade_C', models.IntegerField(default=4, help_text='Any score greater than this will result in a letter Grade of C', verbose_name='Letter Grade C - Greater or Equal To')),
                ('less_than_threshold_grade_C', models.IntegerField(default=6, help_text='Any score less than this will result in a letter Grade of C', verbose_name='and less than')),
                ('greater_eq_threshold_grade_D', models.IntegerField(default=6, help_text='Any score greater than this will result in a letter Grade of D', verbose_name='Letter Grade D - Greater or Equal To')),
                ('less_than_threshold_grade_D', models.IntegerField(default=8, help_text='Any score less than this will result in a letter Grade of D', verbose_name='and less than')),
                ('greater_eq_threshold_grade_F', models.IntegerField(default=8, help_text='Any score greater than this will result in a letter Grade of F', verbose_name='Letter Grade F - Greater Than')),
            ],
            options={
                'verbose_name_plural': 'Letter Grade Thresholds',
            },
        ),
        migrations.CreateModel(
            name='GradeWeights',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('crit_weight', models.IntegerField(default=40, help_text='Critical weight score', verbose_name='Critical Weight Score')),
                ('high_weight', models.IntegerField(default=10, help_text='High weight score', verbose_name='High Weight Score')),
                ('medium_weight', models.IntegerField(default=3, help_text='Medium weight score', verbose_name='Medium Weight Score')),
                ('low_weight', models.IntegerField(default=1, help_text='Low weight score', verbose_name='Low Weight Score')),
            ],
            options={
                'verbose_name_plural': 'Grade Weights',
            },
        ),
    ]
