"""
Django settings for daggerboardproject project.

Generated by 'django-admin startproject' using Django 3.0.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""
import os
import sys
from pathlib import Path

# Get the base directory of your project
BASE_DIR = '/var/www/Daggerboard/'

# Add the 'packages' directory to the sys.path list
sys.path.append(Path(BASE_DIR, "apps", "sbomscanner"))

# Celery settings

CELERY_BROKER_URL = "amqp://localhost"

#: Only add pickle to this list if your broker is secured
#: from unwanted access (see userguide/security.html)
CELERY_RESULT_BACKEND = "db+sqlite:////var/www/Daggerboard/db/tasks.sqlite"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_IMPORTS = ("apps.sbomscanner.tasks", "apps.daggerboard_ui.tasks")

# read config.ini file
basedir = os.getcwd()

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "==_xv2k%xqvnf2zwlgpi2b+=rhq*gymuv58uz4%vbd=2h0fq+g"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["127.0.0.1", "0.0.0.0", "localhost"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "apps.daggerboard_ui",
    "apps.sbomscanner",
    "apps.grading",
    "compressor",
    "django_rq",
    "corsheaders",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "csp.middleware.CSPMiddleware",
]

ROOT_URLCONF = "daggerboardproject.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "daggerboard_ui/templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "csp.context_processors.nonce",
            ],
        },
    },
]

WSGI_APPLICATION = "daggerboardproject.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.path.join(BASE_DIR, "db", "db.sqlite3"),
    },
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True

REST_FRAMEWORK = {
    "DEFAULT_THROTTLE_CLASSES": ["rest_framework.throttling.UserRateThrottle"],
    "DEFAULT_THROTTLE_RATES": {"user": "100/day"},
}

# Authentication backends for LDAP and Local Authentication using django Model
AUTHENTICATION_BACKENDS = [
    "apps.daggerboard_ui.ldap.GroupLDAPBackend",
    "django.contrib.auth.backends.ModelBackend",
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/


STATICFILES_FINDERS = [
    "compressor.finders.CompressorFinder",
]
COMPRESS_PRECOMPILERS = (("text/x-scss", "django_libsass.SassCompiler"),)
LIBSASS_SOURCE_COMMENTS = True
LIBSASS_OUTPUT_STYLE = 'compressed'
LIBSASS_INCLUDE_PATHS = [
    os.path.join(BASE_DIR, "node_modules"),
]
STATIC_ROOT = os.path.join(BASE_DIR, "apps/daggerboard_ui/static")
STATIC_URL = "/static/"
SASS_PRECISION = 8
STATICFILES_DIRS = [os.path.join(BASE_DIR, "apps/daggerboard_ui/static")]

COMPRESS_ENABLED = True
COMPRESS_OFFLINE = True

COMPRESS_ROOT = os.path.join(BASE_DIR, "apps/daggerboard_ui/static")



# media files
MEDIA_ROOT = os.path.join(BASE_DIR, "apps", "sbomscanner", "uploads")
MEDIA_URL = "/uploads/"


# login logout
LOGIN_URL = "/login/"
LOGOUT_REDIRECT_URL = "/login/"

# CSP Policy
CSP_DEFAULT_SRC = [
    "'self'",
    "ajax.googleapis.com",
    "code.jquery.com",
    "cdnjs.cloudflare.com",
    "cdn.datatables.net",
    "cdn.jsdelivr.net",
]

CSP_STYLE_SRC = [
    "'self'",
    "use.fontawesome.com",
    "fonts.googleapis.com",
]

CSP_FONT_SRC = [
    "'self'",
    "cdnjs.cloudflare.com",
    "fonts.gstatic.com",
    "use.fontawesome.com",
]


CSP_SCRIPT_SRC = [
    "'self'",
    "cdnjs.cloudflare.com",
    "code.jquery.com",
    "cdn.jsdelivr.net",
    "ajax.googleapis.com",
    "cdn.datatables.net",
]

# django-rq / redis config
RQ_QUEUES = {
    "default": {
        "HOST": "localhost",
        "DB": 0,
        "PORT": 6379,
        "PASSWORD": "cOIurm1&Fw#ddPg7cPypiHJfL1iq$n72rmVGEul4cOwndVN4WqiUj6ese^p!GLDtT&mhGtaxwU$Tn5sG8$jWTWPVqzGNcuMcmNe",
        "DEFAULT_TIMEOUT": 360,
    }
}
RQ_SHOW_ADMIN_LINK = True

# CORS headers
CORS_ALLOWED_ORIGINS = []

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "user": "100/hour",
    },
}

# session cookie
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
# SECURE_SSL_REDIRECT = True

# email settings
EMAIL_PORT = 25
EMAIL_USE_LOCALTIME = True
EMAIL_USE_TLS = True


# DAGGERBOARD
DAGGERBOARD_BASEDIR = "apps/sbomscanner"
SPDX_BASEDIR = "apps/sbomscanner/spdx_files"
SCANNER_BASEDIR = "apps/sbomscanner"

# SBOM_UPLOAD
UPLOAD_DIRECTORY = "/var/www/Daggerboard/apps/sbomscanner/uploads/sbom"

# PROXY
PROXY_URL = ""

# SCRIPTS
CYCLONEDXTOSPDX = "/var/www/Daggerboard/apps/sbomscanner/cyclonedxtospdx"
JSONTOSPDX = "/var/www/Daggerboard/apps/sbomscanner/jsontospdx.py"

# LOGGING
SBOMPROCESS_LOGPATH = "/var/www/Daggerboard/logs/sbom.log"
DAGGERBOARD_LOGPATH = "logs/daggerboard.log"
CELERY_LOGPATH = "logs/celery.log"

# ARCHIVE
ARCHIVE_PATH = "/var/www/Daggerboard/apps/sbomscanner/archive_spdx"

# DATABASE
DBUSER = "root"
DBHOST = "localhost"
DBPASSWORD = ""

# NVD
NVD_API_KEY = "de2e594e-49d6-4b27-a6b9-6095a523307f"

# REDIS
REDISPWD = "cOIurm1&Fw#ddPg7cPypiHJfL1iq$n72rmVGEul4cOwndVN4WqiUj6ese^p!GLDtT&mhGtaxwU$Tn5sG8$jWTWPVqzGNcuMcmNe"
REDISHOST = "localhost"

# LDAP
LDAP_BIND_PROTECTION = ""

# EMAIL
EMAIL_HOST = ""
EMAIL_PORT = "25"
EMAIL_FROM = ""
