# Generated by Django 3.2.10 on 2022-06-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GradeCalculations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('crit_weight', models.IntegerField(help_text='Critical weight score', max_length=20, verbose_name='Critical Weight Score')),
                ('high_weight', models.IntegerField(help_text='High weight score', max_length=20, verbose_name='High Weight Score')),
                ('medium_weight', models.IntegerField(help_text='Medium weight score', max_length=20, verbose_name='Medium Weight Score')),
                ('low_weight', models.IntegerField(help_text='Low weight score', max_length=20, verbose_name='Low Weight Score')),
            ],
            options={
                'verbose_name_plural': 'Grade Configuration',
            },
        ),
    ]
